# Generated by Django 4.2.7 on 2024-02-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='Product',
            new_name='product',
        ),
    ]
