# Generated by Django 4.2.7 on 2024-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
    ]
