# Generated by Django 4.2.7 on 2024-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0002_remove_compra_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
