# Generated by Django 4.2.7 on 2024-03-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0003_suppliers_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='date',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='price',
            field=models.IntegerField(verbose_name='Valor del gasto'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de contacto'),
        ),
    ]
