# Generated by Django 4.2.7 on 2024-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
