# Generated by Django 4.2.7 on 2024-03-15 05:14

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(orders.models.OroderStatus['CREATED'], 'CREATED'), (orders.models.OroderStatus['PAYED'], 'PAYED'), (orders.models.OroderStatus['COMPLETED'], 'COMPLETED'), (orders.models.OroderStatus['CANCELED'], 'CANCELED')], default=orders.models.OroderStatus['CREATED'], max_length=50),
        ),
        migrations.CreateModel(
            name='OrderPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_info', to='orders.order')),
            ],
            options={
                'verbose_name': 'Información de Recogida',
                'verbose_name_plural': 'Información de Recogida',
            },
        ),
    ]
