# Generated by Django 4.2.7 on 2024-03-13 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pickup_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_info', to='orders.order')),
            ],
            options={
                'verbose_name': 'Información de Recogida',
                'verbose_name_plural': 'Información de Recogida',
            },
        ),
    ]
