# Generated by Django 4.2.7 on 2024-03-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderpickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_datetime',
        ),
    ]
