# Generated by Django 4.2.7 on 2024-03-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_pickup_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpickup',
            name='pickup_datetime',
        ),
    ]
