# Generated by Django 4.2.7 on 2024-03-15 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderpickup_pickup_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpickup',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
