# Generated by Django 4.2.7 on 2024-03-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [

        # migrations.AddField(
        #     model_name='product',
        #     name='status',
        #     field=models.CharField(choices=[('DIS', 'Disponible'), (
        #         'INA', 'Inactivo'), ('OOS', 'Agotado')], default='DIS', max_length=3),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='total_cantidad_disponible',
        #     field=models.IntegerField(
        #         default=0, null=True, verbose_name='Cantidad disponible'),
        # ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        # migrations.CreateModel(
        #     name='Stock',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True,
        #          primary_key=True, serialize=False, verbose_name='ID')),
        #         ('expiration_date', models.DateField(
        #             null=True, verbose_name='Fecha de Vencimiento')),
        #         ('cantidad_disponible', models.IntegerField(
        #             default=0, verbose_name='Cantidad Disponible')),
        #         ('codigo', models.CharField(max_length=50,
        #          unique=True, verbose_name='Codigo')),
        #         ('status', models.CharField(choices=[('DIS', 'Disponible'), (
        #             'INA', 'Inactivo')], default='DIS', max_length=3, verbose_name='Estado')),
        #         ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
        #          to='products.product', verbose_name='Producto')),
        #     ],
        # ),
    ]
