# Generated by Django 4.2.7 on 2024-03-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_amount_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='cantidad_disponible',
        # ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='expiration_date',
        # ),
    ]
