# Generated by Django 4.2.7 on 2024-03-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad_disponible',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('INA', 'Inactivo')], default='DIS', max_length=3, verbose_name='Estado'),
        ),
    ]
