# Generated by Django 4.2.7 on 2024-03-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('INA', 'Inactivo'), ('OOS', 'Agotado')], default='DIS', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='total_cantidad_disponible',
            field=models.IntegerField(default=0, null=True, verbose_name='Cantidad disponible'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(null=True, verbose_name='Fecha de Vencimiento')),
                ('cantidad_disponible', models.IntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('DIS', 'Disponible'), ('INA', 'Inactivo')], default='DIS', max_length=3, verbose_name='Estado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
        ),
    ]
