# Generated by Django 4.2.7 on 2024-02-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Cantidad'),
        ),
    ]
