# Generated by Django 4.2.7 on 2024-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
