# Generated by Django 4.2.7 on 2024-02-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_amount'),
        ('products', '0005_product_cantidad_disponible'),
    ]

    operations = [
    ]
