# Generated by Django 4.2.7 on 2024-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_total_cantidad_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('INA', 'Inactivo'), ('OOS', 'Agotado')], default='DIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cantidad_disponible',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
