# Generated by Django 4.2.7 on 2024-03-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_total_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_cantidad_disponible',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
