# Generated by Django 4.2.7 on 2024-03-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_total_cantidad_disponible'),
        ('products', '0006_product_status_and_more'),
    ]

    operations = [
    ]
